### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by spacepluk** [mike-kelly/monome-layered-enclosures#1]
I just wanted to stop by and thank you for sharing this!
Do you have more pictures it looks amazing!

<3

**Comment by mike-kelly** [comment]
Thanks, sorry for the late reply! There are some more images in the folders, perhaps you didn't see them? I think there are enough to give a reasonable overview.

**Comment by spacepluk** [comment]
yeah, I found the rest of the images right after I posted this, hehe.  Thanks again!
